name: CompanyEconomy
version: 1.9
main: com.foxsrv.companyeconomy.CompanyEconomy
api-version: 1.20
depend: [Vault]

commands:
  company:
    usage: /company hire <player> [role] [company]
    description: Company management command
